CREATE TABLE `TBL_CATEGORIAS_CONSUMO` (
    `CODIGO_CATEGORIA`	INT,
    `NOMBRE_CATEGORIA`	VARCHAR(512),
    `CIUDAD`	VARCHAR(512),
    `DEPARTAMENTO`	VARCHAR(512)
);

INSERT INTO `TBL_CATEGORIAS_CONSUMO` (`CODIGO_CATEGORIA`, `NOMBRE_CATEGORIA`, `CIUDAD`, `DEPARTAMENTO`) VALUES
	('1', 'Electrónica', 'Bogotá', 'Distrito Capital'),
	('2', 'Ropa', 'Bogotá', 'Distrito Capital'),
	('3', 'Alimentos', 'Bogotá', 'Distrito Capital'),
	('4', 'Juguetes', 'Bogotá', 'Distrito Capital'),
	('5', 'Muebles', 'Bogotá', 'Distrito Capital'),
	('6', 'Deportes', 'Bogotá', 'Distrito Capital'),
	('7', 'Libros', 'Bogotá', 'Distrito Capital'),
	('8', 'Belleza', 'Bogotá', 'Distrito Capital'),
	('9', 'Automotriz', 'Bogotá', 'Distrito Capital'),
	('10', 'Tecnología', 'Bogotá', 'Distrito Capital'),
	('11', 'Hogar', 'Bogotá', 'Distrito Capital'),
	('12', 'Salud', 'Bogotá', 'Distrito Capital'),
	('13', 'Mascotas', 'Bogotá', 'Distrito Capital'),
	('14', 'Viajes', 'Bogotá', 'Distrito Capital'),
	('15', 'Joyería', 'Bogotá', 'Distrito Capital'),
	('16', 'Ferretería', 'Bogotá', 'Distrito Capital'),
	('17', 'Papelería', 'Bogotá', 'Distrito Capital'),
	('18', 'Fotografía', 'Bogotá', 'Distrito Capital'),
	('19', 'Música', 'Bogotá', 'Distrito Capital'),
	('20', 'Jardinería', 'Bogotá', 'Distrito Capital'),
	('21', 'Electrónica', 'Medellín', 'Antioquia'),
	('22', 'Ropa', 'Medellín', 'Antioquia'),
	('23', 'Alimentos', 'Medellín', 'Antioquia'),
	('24', 'Juguetes', 'Medellín', 'Antioquia'),
	('25', 'Muebles', 'Medellín', 'Antioquia'),
	('26', 'Deportes', 'Medellín', 'Antioquia'),
	('27', 'Libros', 'Medellín', 'Antioquia'),
	('28', 'Belleza', 'Medellín', 'Antioquia'),
	('29', 'Automotriz', 'Medellín', 'Antioquia'),
	('30', 'Tecnología', 'Medellín', 'Antioquia'),
	('31', 'Hogar', 'Medellín', 'Antioquia'),
	('32', 'Salud', 'Medellín', 'Antioquia'),
	('33', 'Mascotas', 'Medellín', 'Antioquia'),
	('34', 'Viajes', 'Medellín', 'Antioquia'),
	('35', 'Joyería', 'Medellín', 'Antioquia'),
	('36', 'Ferretería', 'Medellín', 'Antioquia'),
	('37', 'Papelería', 'Medellín', 'Antioquia'),
	('38', 'Fotografía', 'Medellín', 'Antioquia'),
	('39', 'Música', 'Medellín', 'Antioquia'),
	('40', 'Jardinería', 'Medellín', 'Antioquia'),
	('41', 'Electrónica', 'Cali', 'Valle del Cauca'),
	('42', 'Ropa', 'Cali', 'Valle del Cauca'),
	('43', 'Alimentos', 'Cali', 'Valle del Cauca'),
	('44', 'Juguetes', 'Cali', 'Valle del Cauca'),
	('45', 'Muebles', 'Cali', 'Valle del Cauca'),
	('46', 'Deportes', 'Cali', 'Valle del Cauca'),
	('47', 'Libros', 'Cali', 'Valle del Cauca'),
	('48', 'Belleza', 'Cali', 'Valle del Cauca'),
	('49', 'Automotriz', 'Cali', 'Valle del Cauca'),
	('50', 'Tecnología', 'Cali', 'Valle del Cauca'),
	('51', 'Hogar', 'Cali', 'Valle del Cauca'),
	('52', 'Salud', 'Cali', 'Valle del Cauca'),
	('53', 'Mascotas', 'Cali', 'Valle del Cauca'),
	('54', 'Viajes', 'Cali', 'Valle del Cauca'),
	('55', 'Joyería', 'Cali', 'Valle del Cauca'),
	('56', 'Ferretería', 'Cali', 'Valle del Cauca'),
	('57', 'Papelería', 'Cali', 'Valle del Cauca'),
	('58', 'Fotografía', 'Cali', 'Valle del Cauca'),
	('59', 'Música', 'Cali', 'Valle del Cauca'),
	('60', 'Jardinería', 'Cali', 'Valle del Cauca');